config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations

  resource :profile, only: [:edit, :update]
  resource :password, only: [:edit, :update]

  resources :players, except: :show do
    collection do
      get :ranked
    end
  end
  resources :removals, only: [:new, :create]

  resource :schedule, only: [:edit, :update]

  resources :games do
    collection do
      get :next
      post :schedule
    end

    member do
      get :respond
      post :override
      post :remind
      post :cancel
      post :reschedule
    end
  end

  resources :quips, except: [:show, :destroy]

  resource :push_subscription, only: [:create, :destroy]

  authenticate :user, -> (user) { Authorizer.new(user: user).admin? } do
    mount GoodJob::Engine => 'good_job'
  end

  get "manifest" => "manifest#show", as: :manifest, defaults: { format: :json }

  root to: 'games#next'
end

app/controllers/removals_controller.rb
class RemovalsController < ApplicationController
  include AccessTokenController

  before_action :set_player_by_params_access_token!
  decorates_assigned :player

  def new
  end

  def create
    if player.email != params[:removal][:email]
      redirect_to new_removal_path(access_token: player.access_token), alert: "Your email didn't match our records. Please check it again."
    else
      player.destroy
      redirect_to players_path, notice: 'Removed you from the list. Let us know if you ever want to come back!'
    end
  end
end

app/views/removals/new.html.haml
- layout.page_title = 'Remove Me'

.page-header
  %h1 Remove Me from the List

= form_with url: removals_path, method: :post, scope: :removal do |f|
  = hidden_field_tag :access_token, player.access_token

  .row.mb-3
    = f.label :email, 'Confirm your email', class: 'col-form-label col-12 col-md-3 col-lg-2'
    .col-12.col-md-6.col-lg-3
      = f.text_field :email, class: 'form-control', value: player.email

  .row
    .col-12.offset-md-3.col-md-9.offset-lg-2.col-lg-10
      = f.submit 'Remove Me', class: 'btn btn-warning'
      = link_to 'Go Back', players_path, class: 'btn btn-link'