config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations

  resource :profile, only: [:edit, :update]
  resource :password, only: [:edit, :update]

  resources :players, except: :show do
    collection do
      get :ranked
    end
  end
  resources :removals, only: [:new, :create]

  resource :schedule, only: [:edit, :update]

  resources :games do
    collection do
      get :next
      post :schedule
    end

    member do
      get :respond
      post :override
      post :remind
      post :cancel
      post :reschedule
    end
  end

  resources :quips, except: [:show, :destroy]

  resource :push_subscription, only: [:create, :destroy]

  authenticate :user, -> (user) { Authorizer.new(user: user).admin? } do
    mount GoodJob::Engine => 'good_job'
  end

  get "manifest" => "manifest#show", as: :manifest, defaults: { format: :json }

  root to: 'games#next'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :location
  has_many :responses, dependent: :destroy
  has_many :players, through: :responses
  has_many :confirmed_players, -> { merge(Response.confirmed) }, through: :responses, source: :player
  has_many :declined_players, -> { merge(Response.declined) }, through: :responses, source: :player
  before_validation :ensure_location

  scope :upcoming, -> { where('starts_at > NOW()') }
  scope :past, -> { where('starts_at < NOW()') }
  scope :on, -> { where(canceled: false) }

  def self.seed
    find_or_create_by!(starts_at: Current.schedule.next_occurrence.start_time)
  end

  def respond(player, playing)
    responses.where(player_id: player).destroy_all
    responses.create(player_id: player.id, playing: playing)
  end

  def unconfirmed_players
    Player.active - confirmed_players
  end

  def upcoming?
    starts_at > Time.zone.now
  end

  def on?
    !canceled?
  end

private

  def ensure_location
    self.location = Current.schedule.location if location.blank?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include AccessTokenController

  before_action :authenticate_user!, only: [:edit, :update, :schedule, :remind, :cancel, :reschedule]
  before_action :find_game, only: [:show, :edit, :update, :respond, :override, :remind, :cancel, :reschedule]
  before_action :set_player_by_params_access_token!, only: :respond
  before_action :set_player_from_session, only: [:next, :show]
  before_action :set_quip, only: [:next, :show]
  before_action :set_locations, only: [:edit, :update]

  after_action :set_access_token, only: [:respond]

  decorates_assigned :game, :games, :player, :quip, :default_schedule

  def index
    @games = Game
      .includes(:confirmed_players, :location)
      .order(starts_at: :desc)
      .page(params[:page])
      .per(25)

    @default_schedule = Current.schedule
  end

  def show
    respond_to do |format|
      format.html
      format.ics do
        send_data Event.new(game: @game, view_context: view_context).to_ical, filename: 'ultimate.ics'
      end
    end
  end

  def edit
  end

  def update
    if @game.update(game_params)
      SendUpdatePushNotificationJob.perform_later(@game)
      redirect_to games_path, notice: 'Game was successfully updated.'
    else
      render :edit, status: :unprocessable_content
    end
  end

  def next
    @game = Game.upcoming.first
  end

  def schedule
    game = Game.seed
    SendNewGamePushNotificationJob.perform_later(game) if game.previously_new_record?
    redirect_to game, notice: 'Scheduled the next game.'
  end

  def respond
    playing = params[:playing] == 'yes'
    notice = playing ? 'See you there!' : 'Maybe next time.'

    @game.respond(@player, playing)
    SendPushNotificationsJob.perform_later(@game, @player, playing)

    redirect_to @game, notice: notice
  end

  def override
    player = Player.find(params[:player_id])

    if params[:played] == 'yes'
      @game.respond(player, true)
      redirect_to @game, notice: "Added #{player.short_name} to the game."
    else
      @game.responses.where(player_id: player.id).destroy_all
      redirect_to @game, notice: "Removed #{player.short_name} from the game."
    end
  end

  def remind
    notifier.send_reminder
    redirect_to @game, notice: 'Sent your message.'
  end

  def cancel
    @game.update(canceled: true)
    notifier.send_cancellation
    SendCancellationPushNotificationJob.perform_later(@game)
    redirect_to @game, notice: 'Canceled the game and sent your message.'
  end

  def reschedule
    @game.update(canceled: false)
    notifier.send_reschedule
    SendReschedulePushNotificationJob.perform_later(@game)
    redirect_to @game, notice: 'Rescheduled the game and sent your message.'
  end

private

  def notifier
    GameNotifier.new(game: @game, sender: current_user, body: params[:message])
  end

  def find_game
    @game = Game.find(params[:id])
  end

  def set_quip
    @quip = RandomQuip.call
  end

  def set_access_token
    cookies.permanent[:access_token] = @player.access_token
  end

  def set_locations
    @locations = Location.order(:name)
  end

  def game_params
    params.require(:game).permit(:canceled, :location_id, :starts_at)
  end
end

app/views/games/_actions.html.haml
- if authorizer.admin? && game&.upcoming?
  .subnav
    %ul.nav
      - if game.canceled?
        %li.nav-item= render 'reschedule'
      - else
        %li.nav-item= link_to 'Edit this Game', edit_game_path(game), class: 'nav-link'
        %li.nav-item= render 'reminder'
        %li.nav-item= render 'cancellation'

app/views/games/_admin_actions.html.haml
- unless game.upcoming?

  %h2.mb-4 Add or Remove Players

  .edit-players
    .row.mb-4
      .col-12.col-lg-6
        = form_tag override_game_url(game), class: 'row row-cols-lg-auto g-3 align-items-center' do
          = hidden_field_tag :played, 'yes'
          = label_tag :player_id, 'Player Name', class: 'visually-hidden'
          .col-12= select_tag :player_id, options_from_collection_for_select(game.unconfirmed_players, :id, :short_name), class: 'form-select me-2'
          .col-12= button_tag 'Add', class: 'btn btn-primary'

    .row
      .col-12.col-lg-6
        = form_tag override_game_url(game), class: 'row row-cols-lg-auto g-3 align-items-center' do
          = hidden_field_tag :played, 'no'
          = label_tag :player_id, 'Player Name', class: 'visually-hidden'
          .col-12= select_tag :player_id, options_from_collection_for_select(game.confirmed_players, :id, :short_name), class: 'form-select me-2'
          .col-12= button_tag 'Remove', class: 'btn btn-warning'

app/views/games/_cancellation.html.haml
= render ModalLinkComponent.new(title: 'Cancel this Game', url: cancel_game_path(game), button_text: 'Cancel Game') do
  %p
    Originally on
    %strong= game.date

  .form-group
    = label_tag :message, 'Message'
    = text_area_tag :message, 'Sorry, folks. I have to cancel frisbee this week.', rows: 5, class: 'form-control'

app/views/games/_form.html.haml
= form_for game do |f|
  .row.mb-3
    = f.label :location, class: 'col-form-label col-12 col-md-2'
    .col-12.col-md-4
      = f.collection_select :location_id, @locations, :id, :name, {}, class: 'form-select'

  .row.mb-3
    = f.label :starts_at, class: 'col-form-label col-12 col-md-2'
    .col-12.col-md-3
      = f.datetime_select :starts_at, {}, class: 'form-select mb-1'

  .row
    .col-12.offset-md-2.col-md-10
      = f.submit class: 'btn btn-primary'
      = link_to 'Go Back', (game.new_record? ? games_path : game), class: 'btn btn-link'

app/views/games/_game.html.haml
%h3.mb-3= pluralize game.confirmed_players.size, 'player'

.game-details
  %dl.row
    %dt.col-12.col-md-2 When
    %dd.col-12.col-md-10
      %p.mb-0= game.date
      %p.mb-0.text-muted= game.relative_date

    %dt.col-12.col-md-2 Where
    %dd.col-12.col-md-10= game.location.link

    %dt.col-12.col-md-2
      - if game.canceled?
        Who Signed Up
      - elsif game.upcoming?
        Who’s In
      - else
        Who Played
    %dd.col-12.col-md-10
      = game.confirmed_player_names

    %dt.col-12.col-md-2= game.upcoming? ? "Who’s Out" : "Who Declined"
    %dd.col-12.col-md-10= game.declined_player_names

  - if game.upcoming? && game.on?
    %p= game.calendar_link

- if game.upcoming? && game.on? && player.present?
  %hr
  = render 'player_actions'

- elsif authorizer.admin?
  %hr
  = render 'admin_actions' if authorizer.admin?

app/views/games/_player_actions.html.haml
.player-actions
  %h2.mb-3= "RSVP as #{player.short_name}"

  .response.mb-2= link_to quip.confirmation, respond_game_url(game, access_token: player.access_token, playing: 'yes'), class: 'btn btn-primary me-2', data: { turbo_prefetch: false }
  .response= link_to quip.rejection, respond_game_url(game, access_token: player.access_token, playing: 'no'), class: 'btn btn-secondary', data: { turbo_prefetch: false }

app/views/games/_reminder.html.haml
= render ModalLinkComponent.new(title: 'Send a Reminder', url: remind_game_path(game), button_text: 'Send Reminder') do
  %p
    For the game on
    %strong= game.date

  .form-group
    = label_tag :message, 'Message'
    = text_area_tag :message, 'Who can make it?', rows: 5, class: 'form-control'

app/views/games/_reschedule.html.haml
= render ModalLinkComponent.new(title: 'Reschedule this Game', url: reschedule_game_path(game), button_text: 'Reschedule Game') do
  %p
    For
    %strong= game.date

  .form-group
    = label_tag :message, 'Message'
    = text_area_tag :message, 'The game is back on!', rows: 5, class: 'form-control'

app/views/games/edit.html.haml
- layout.page_title = 'Edit Game'

.page-header
  %h1 Edit Game

= render 'form'

app/views/games/index.html.haml
- layout.page_title = 'Games'

.page-header
  %h1 Games
  - if authorizer.admin?
    .subnav
      %ul.nav
        - if Game.upcoming.empty?
          %li.nav-item
            = button_to "Schedule #{default_schedule.day}'s Game", schedule_games_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Change the Schedule', edit_schedule_path, class: 'nav-link'


%p.lead.my-4= default_schedule.summary

.table-responsive
  %table.table.table-hover.games
    %thead.thead-dark
      %tr
        %th.date Date
        %th.location Location
        %th.players Attendance

    %tbody
      - games.each do |game|
        %tr{class: game.canceled? ? 'canceled' : 'on'}
          %td.name= link_to(game.canceled? ? "#{game.date} (canceled)" : game.date, game)
          %td.location= game.location.link
          %td.players= game.canceled? ? '—' : pluralize(game.confirmed_players.size, 'player')

.d-flex.justify-content-center.mt-4
  = paginate @games

app/views/games/next.html.haml
- layout.page_title = 'Next Game'

.page-header
  %h1 Next Game
  = render 'actions'

- if game

  - if game.canceled?
    %p.lead It’s canceled. Maybe next week!
  - else
    = render game

- else
  %p.lead Nothing scheduled yet.

app/views/games/show.html.haml
- layout.page_title = "Game ##{game.id}"

.page-header
  %h1
    = "Game ##{game.id}"
    = '(Canceled)' if game.canceled?
  = render 'actions'

= render game