config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations

  resource :profile, only: [:edit, :update]
  resource :password, only: [:edit, :update]

  resources :players, except: :show do
    collection do
      get :ranked
    end
  end
  resources :removals, only: [:new, :create]

  resource :schedule, only: [:edit, :update]

  resources :games do
    collection do
      get :next
      post :schedule
    end

    member do
      get :respond
      post :override
      post :remind
      post :cancel
      post :reschedule
    end
  end

  resources :quips, except: [:show, :destroy]

  resource :push_subscription, only: [:create, :destroy]

  authenticate :user, -> (user) { Authorizer.new(user: user).admin? } do
    mount GoodJob::Engine => 'good_job'
  end

  get "manifest" => "manifest#show", as: :manifest, defaults: { format: :json }

  root to: 'games#next'
end

app/models/player.rb
class Player < ApplicationRecord
  before_create :generate_access_token, unless: -> { access_token.present? }

  before_validation :generate_short_name, if: -> { short_name.blank? }
  validates_presence_of :first_name, :last_name, :short_name, :email

  default_scope -> { order(first_name: :asc) }
  scope :active, -> { where(deleted_at: nil) }
  scope :emailable, -> { active.where.not(email: nil).where(retired: false) }

  has_one :user, primary_key: :email, foreign_key: :email

  has_many :responses
  has_many :games, through: :responses
  has_many :confirmed_games, -> { on.merge(Response.confirmed) }, through: :responses, source: :game

  def name
    "#{first_name} #{last_name}"
  end

  def worthy?
    confirmed_games.present? && confirmed_games.last.starts_at > 1.month.ago
  end

  def destroy
    update(deleted_at: Time.zone.now)
  end

  private

  def generate_short_name
    self.short_name = name
  end

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.where(access_token: self.access_token).exists?
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  include AccessTokenController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_player, only: [:edit, :update, :destroy]
  before_action :set_player_from_session, only: [:index]

  decorates_assigned :player, :players

  def index
    @players = Player.active.includes(:confirmed_games)
  end

  def ranked
    @players = PlayerRanker
      .by_games_played(since: params[:since].to_i.months.ago)
      .limit(10)
  end

  def new
    @player = Player.new
  end

  def edit
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      PopulatePlayerShortNamesJob.perform_later
      redirect_to players_url, notice: 'Player was successfully created.'
    else
      flash.now[:alert] = "Failed to create player: #{@player.errors.to_a.to_sentence}"
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @player.update(player_params)
      PopulatePlayerShortNamesJob.perform_later
      redirect_to players_url, notice: 'Player was successfully updated.'
    else
      flash.now[:alert] = "Failed to update player: #{@player.errors.to_a.to_sentence}"
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    if @player.destroy
      redirect_to players_url, notice: 'Player was successfully removed.'
    else
      redirect_to players_url, alert: "Failed to remove player: #{@player.errors.to_a.to_sentence}"
    end
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:access_token, :email, :first_name, :last_name, :phone, :retired)
  end
end

app/views/players/_actions.html.haml
.subnav
  %ul.nav
    - if authorizer.admin?
      %li.nav-item
        = link_to 'Add a Player', new_player_path, class: 'nav-link'

    - if player.present?
      %li.nav-item
        = link_to 'Remove Me from the List', new_removal_path(access_token: player.access_token), class: 'nav-link text-warning'

app/views/players/_form.html.haml
= form_for player do |f|
  .row.mb-3
    = f.label :first_name, class: 'col-form-label col-12 col-md-2'
    .col-12.col-md-6.col-lg-3
      = f.text_field :first_name, class: 'form-control'

  .row.mb-3
    = f.label :last_name, class: 'col-form-label col-12 col-md-2'
    .col-12.col-md-6.col-lg-3
      = f.text_field :last_name, class: 'form-control'

  .row.mb-3
    = f.label :email, class: 'col-form-label col-12 col-md-2'
    .col-12.col-md-6.col-lg-3
      = f.text_field :email, class: 'form-control'

  .row.mb-3
    = f.label :phone, class: 'col-form-label col-12 col-md-2'
    .col-12.col-md-6.col-lg-3
      = f.text_field :phone, class: 'form-control'
      %small.form-text.text-muted Optional

  .row.mb-3
    .col-12.offset-md-2.col-md-10
      .form-check
        = f.check_box :retired, class: 'form-check-input'
        = f.label :retired, class: 'form-check-label'

  .row
    .col-12.offset-md-2.col-md-10
      = f.submit class: 'btn btn-primary'
      = link_to 'Go Back', players_path, class: 'btn btn-link'

app/views/players/_player.html.haml
%tr{class: player.css_class}
  %td.icon= player.attendance_icon
  %td.name= authorizer.admin? ? link_to(player.name, "mailto:#{player.email}") : player.name
  %td.attendance= player.attendance

  - if authorizer.admin?
    %td.phone= player.phone
    %td.actions
      = player.edit_link
      = player.remove_link

app/views/players/edit.html.haml
- layout.page_title = 'Edit Player'

.page-header
  %h1 Edit Player

= render 'form'

app/views/players/index.html.haml
- layout.page_title = 'Players'

.page-header
  %h1 Players
  = render 'actions'

.row
  .col-12.col-lg-6
    %h3.visually-hidden Everyone

    .table-responsive
      %table.table.table-hover.players
        %thead.thead-dark
          %tr
            %th.icon
            %th.name Name
            %th.attendance Attendance

            - if authorizer.admin?
              %th.phone Phone
              %th.actions

        %tbody
          = render players

  .col-12.col-lg-6
    %h3.visually-hidden By Games Played

    = form_with url: ranked_players_url(format: 'json'),
        class: 'mt-4',
        data: { controller: 'player-chart', action: 'player-chart#load:prevent' } do |f|
      .d-flex.justify-content-center.align-items-center.my-3.w-50.mx-auto
        = f.label :since, 'Past'

        .input-group.mx-3
          = f.text_field :since, value: 6, class: 'form-control', data: { player_chart_target: 'input' }
          %span.input-group-text Months

        = f.submit 'Go', class: 'btn btn-primary'

      %canvas{ data: { player_chart_target: 'chart' } }

app/views/players/new.html.haml
- layout.page_title = 'New Player'

.page-header
  %h1 New Player

= render 'form'