config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations

  resource :profile, only: [:edit, :update]
  resource :password, only: [:edit, :update]

  resources :players, except: :show do
    collection do
      get :ranked
    end
  end
  resources :removals, only: [:new, :create]

  resource :schedule, only: [:edit, :update]

  resources :games do
    collection do
      get :next
      post :schedule
    end

    member do
      get :respond
      post :override
      post :remind
      post :cancel
      post :reschedule
    end
  end

  resources :quips, except: [:show, :destroy]

  resource :push_subscription, only: [:create, :destroy]

  authenticate :user, -> (user) { Authorizer.new(user: user).admin? } do
    mount GoodJob::Engine => 'good_job'
  end

  get "manifest" => "manifest#show", as: :manifest, defaults: { format: :json }

  root to: 'games#next'
end

app/models/layout.rb
class Layout
  include ActiveModel::Model
  attr_accessor :application_name, :controller, :page_title, :view_context

  def full_page_title
    if page_title.present?
      "#{page_title} — #{application_name}"
    else
      application_name
    end
  end

  def body_class
    [controller.controller_name, controller.action_name].join(' ')
  end

  def nav_link(text, url, options = {})
    active = view_context.current_page?(url) && 'active'

    view_context.tag.li(class: ['nav-item', active].compact.join(' ')) do
      view_context.link_to text, url, options.merge(class: 'nav-link')
    end
  end

  def quips_link
    count = Quip.pending.count
    content = if view_context.authorizer.admin? && count.positive?
      badge = view_context.tag.span(count, class: 'badge badge-info align-middle')
      sr = view_context.tag.span('to review', class: 'sr-only')
      view_context.safe_join(['Quips', badge, sr], ' ')
    else
      'Quips'
    end

    nav_link content, view_context.quips_path
  end

  def flash_messages
    view_context.flash
      .map { AlertComponent.new(type: _1, message: _2) }
      .reject(&:blank?)
      .map { view_context.render(_1) }
      .then { view_context.safe_join(_1) }
  end
end

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no")
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta(name="apple-mobile-web-app-status-bar-style" content="black")
    %link{rel: "icon", href: asset_path("icon.svg"), type: "image/svg+xml"}
    %link{rel: "icon", href: asset_path("icon.png"), type: "image/png"}
    %link{rel: "apple-touch-icon", href: asset_path("icon.png")}
    %link{rel: "manifest", href: manifest_path}
    = csrf_meta_tags
    - if user_signed_in?
      %meta(name="vapid-public-key" content="#{Rails.application.credentials.vapid.public_key}")

    %title= layout.full_page_title

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags

  %body{class: layout.body_class}
    %nav.navbar.navbar-expand-lg.bg-dark.fixed-top(data-bs-theme="dark")
      .container
        = link_to 'Foxy Lady Ultimate', root_path, class: 'navbar-brand'

        %button.navbar-toggler(type="button" data-bs-toggle="collapse" data-bs-target="#navbar-main" aria-controls="navbar-main" aria-expanded="false" aria-label="Toggle navigation")
          %span.navbar-toggler-icon

        .collapse.navbar-collapse#navbar-main
          %ul.navbar-nav.me-auto
            = layout.nav_link 'Games', games_path
            = layout.nav_link 'Players', players_path
            = layout.nav_link 'Quips', quips_path if authorizer.admin?

          %ul.navbar-nav.ms-auto
            - if user_signed_in?
              %li.nav-item.dropdown
                %a.nav-link.dropdown-toggle(href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false")
                  = current_user.first_name
                %ul.dropdown-menu.dropdown-menu-end
                  %li= link_to 'Edit Profile', edit_profile_path, class: 'dropdown-item'
                  %li= link_to 'Change Password', edit_password_path, class: 'dropdown-item'
                  %li= link_to 'Sign Out', destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete }
            - else
              = layout.nav_link 'Sign In', new_user_session_path

    .container
      = layout.flash_messages
      = yield

app/views/layouts/game_mailer.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    :css
      body {
        padding: 5px;
        font-family: "Lucida Grande", "Helvetica", "Arial", sans-serif;
        font-size: 10pt;
      }

      a {
        text-decoration: none;
        color: #007fff;
      }

      a.text-secondary {
        color: #868e96;
      }

      a:hover {
        text-decoration: underline;
      }

      p {
        line-height: 1.5em;
        margin-bottom: 1.5em;
      }

      .separator {
        margin: auto 0.5em;
      }

      .declination {
        color: #9fbfdf;
      }

  %body
    = yield